### ISSUE TITLE
How would you project a field out of a nested object?

### ISSUE THREAD

**Issue by isaacsanders** [yesoreyeram/uql#15]
Say that my data looks like:

```json
[
  {
    "title": "Pull Request Title 1",
    "repository": {
      "nameWithOwner": "org/repo"
    },
    "author": {
      "login": "isaacsanders"
    }
  },
  {
    "title": "Pull Request Title 2",
    "repository": {
      "nameWithOwner": "org/repo"
    },
    "author": {
      "login": "yesoreyeram"
    }
  }
]
```

How would one generate a table in Grafana that looks the table below?

| Title | Author | Repository |
|------|----|----|
| Pull Request Title 1 | isanders | org/repo |
| Pull Request Title 2 | yesoreyeram | org/repo |

**Comment by isaacsanders** [comment]
Right now I have a pile of Jsonata, but I don't prefer it much.

**Comment by flysand7** [comment]
Use dot inside the double quotes to access a field.

```
parse-json
| project "Title", "Author"="author.login", "Repository"="repository.nameWithOwner"
```

**Comment by isaacsanders** [comment]
Much appreciated! I’ll close this tomorrow if I can make it work!
